import Header from "@/components/dashboard/Header";
import { AuthProvider } from "@/context/AuthContext";
import { FetchError, http } from "@/lib/fetch";
import { User } from "@/types/user";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";

export const dynamic = "force-dynamic";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getCurrentUser(): Promise<User | null> {
  try {
    // Chama o /users/me do asheos-api
    const response = await http.get("/users/me");
    return response.data;
  } catch (error) {
    if (error instanceof FetchError && error.response.status === 401)
      // Se der erro (token inválido, etc), remove o cookie e retorna null
      (await cookies()).delete("token");
    return null;
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider initialUser={user}>
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
